Repository uasoft-indonesia/badaso-content-module, pull requests merged in 2021-06, with the labels that each got.

#38 Merge develop to main
  CONTRIBUTING.md
  src/Commands/BadasoContentDummySeeder.php
  src/Providers/BadasoContentModuleServiceProvider.php
  src/Seeder/ContentTableSeeder.php
Labels: backend

#40 Change content module route similar to blog module
  src/Routes/api.php
  src/resources/js/api/modules/badaso-content.js
Labels: backend, bugfix, frontend

#41 Merge develop to main
  src/Routes/api.php
  src/resources/js/api/modules/badaso-content.js
Labels: backend, frontend

#43 Implement management file
  src/resources/js/components/BadasoContent.vue
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/read.vue
Labels: bugfix, frontend

#42 add excluded router for analytics
  src/resources/js/router/excludeRouter.js
Labels: bugfix, frontend

#44 Merge develop to main
  src/resources/js/components/BadasoContent.vue
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/read.vue
  src/resources/js/router/excludeRouter.js
Labels: frontend

#46 Apply fixes from StyleCI
  src/Seeder/ContentRolePermissionsSeeder.php
Labels: backend

#45 Enhancement/upgrade laravel 8
  src/Providers/BadasoContentModuleServiceProvider.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentRolePermissionsSeeder.php
  src/Swagger/content.php
  src/resources/js/router/routes.js
Labels: backend, enhancement, frontend

#47 Merge develop to main
  src/Providers/BadasoContentModuleServiceProvider.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentRolePermissionsSeeder.php
  src/Swagger/content.php
  src/resources/js/router/routes.js
Labels: backend, frontend

#49 change url behavior on content read
  src/resources/js/pages/content/read.vue
Labels: enhancement, frontend

#50 Merge develop to main
  src/resources/js/pages/content/read.vue
Labels: frontend

#48 change url on content read
  src/resources/js/pages/content/read.vue
Labels: bugfix, frontend

#54 Apply fixes from StyleCI
  src/Commands/BadasoContentSetup.php
  src/Routes/api.php
Labels: backend

#53 change hidden table and swagger uri
  src/Commands/BadasoContentSetup.php
  src/Routes/api.php
  src/Swagger/content_module.php
Labels: backend, bugfix

#58 Add draggable
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
Labels: feature, frontend

#57 Add draggable
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
Labels: feature, frontend

#56 Add media base url meta
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/pages/content/read.vue
Labels: feature, frontend

#55 Add media base url meta
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/pages/content/read.vue
Labels: feature, frontend

#59 Merge develop to main
  composer.json
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/read.vue
Labels: dependencies, frontend

#61 fix ordering
  src/resources/js/components/BadasoContent.vue
Labels: feature, frontend

#60 fix content manager
  src/resources/js/components/BadasoContent.vue
Labels: feature, frontend
