Repository uasoft-indonesia/badaso-content-module, pull requests merged in 2021-05, with the labels that each got.

#3 Bugfix/content manager
  composer.json
  src/Seeder/ContentPermissionsSeeder.php
  src/resources/js/pages/content/fill.vue
Labels: backend, dependencies, frontend

#5 Apply fixes from StyleCI
  src/Controllers/ContentController.php
  src/Migrations/2021_04_01_090258_create_content_table.php
  src/Seeder/ContentTableSeeder.php
Labels: backend

#4 Merge develop to master
  .styleci.yml
  composer.json
  src/Controllers/ContentController.php
  src/Migrations/2021_04_01_090258_create_content_table.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/resources/js/pages/content/fill.vue
Labels: backend, dependencies, frontend

#6 Merge develop to main
  composer.json
Labels: dependencies

#8 Apply fixes from StyleCI
  src/Controllers/ContentController.php
  src/Migrations/2021_04_01_090258_create_content_table.php
  src/Routes/api.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/Swagger/content_module.php
Labels: backend

#7 add swagger content manager
  src/Commands/BadasoContentSetup.php
  src/Controllers/ContentController.php
  src/Providers/BadasoModuleContentServiceProvider.php
  src/Routes/api.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/Swagger/content_module.php
  src/resources/js/api/modules/badaso-content.js
Labels: backend, feature, frontend

#9 Merge develop to main
  composer.json
Labels: dependencies

#10 Rebase develop with main
  src/Commands/BadasoContentSetup.php
  src/Controllers/ContentController.php
  src/Providers/BadasoModuleContentServiceProvider.php
  src/Routes/api.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/Swagger/content_module.php
  src/resources/js/api/modules/badaso-content.js
Labels: backend, frontend

#17 Add seeder and bugfix
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/resources/js/pages/content/edit.vue
Labels: backend, feature, frontend

#18 Merge develop to main
  README.md
  composer.json
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/resources/js/pages/content/edit.vue
Labels: backend, dependencies, frontend

#20 change command
  src/Commands/BadasoContentSetup.php
Labels: backend, feature

#21 Fix composer versioning
  composer.json
Labels: bugfix, dependencies

#22 Merge develop to main
  README.md
  composer.json
  src/Commands/BadasoContentSetup.php
Labels: backend, dependencies

#24 Change default prefix
  src/resources/js/router/routes.js
Labels: bugfix, frontend

#27 change name provider class badaso content module
  CONTRIBUTING.md
Labels: bugfix

#28 change file provider class badaso content module
  CONTRIBUTING.md
  composer.json
  src/Providers/BadasoContentModuleServiceProvider.php
Labels: backend, bugfix, dependencies

#30 Apply fixes from StyleCI
  src/Seeder/ContentRolePermissionsSeeder.php
Labels: backend

#29 Bugfix/seeder change
  CONTRIBUTING.md
  README.md
  src/Commands/BadasoContentSetup.php
  src/Providers/BadasoContentModuleServiceProvider.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentRolePermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
Labels: backend

#32 Apply fixes from StyleCI
  src/Seeder/ContentRolePermissionsSeeder.php
Labels: backend

#33 Merge develop to main
  CONTRIBUTING.md
  README.md
  composer.json
  src/Commands/BadasoContentSetup.php
  src/Providers/BadasoContentModuleServiceProvider.php
  src/Seeder/ContentFixedMenuItemSeeder.php
  src/Seeder/ContentMenusSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/Seeder/ContentPermissionsSeeder.php
  src/Seeder/ContentRolePermissionsSeeder.php
  src/Seeder/ContentTableSeeder.php
  src/resources/js/router/routes.js
Labels: backend, dependencies, frontend

#36 Apply fixes from StyleCI
  src/Seeder/ContentRolePermissionsSeeder.php
Labels: backend
