Repository uasoft-indonesia/badaso-content-module, pull requests merged in 2021-08, with the labels that each got.

#75 Apply fixes from StyleCI
  src/Controllers/ContentController.php
Labels: backend

#77 Apply fixes from StyleCI
  src/Controllers/ContentController.php
Labels: backend

#74 Remove old concept of file manager
  src/Controllers/ContentController.php
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/fill.vue
  src/resources/js/pages/content/read.vue
Labels: enhancement, frontend, backend

#76 Remove old concept of file manager
  src/Controllers/ContentController.php
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/fill.vue
  src/resources/js/pages/content/read.vue
Labels: enhancement, frontend, backend

#78 Prepare 2.0.0-rc.5
  src/Controllers/ContentController.php
  src/resources/js/components/BadasoContentRead.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/fill.vue
  src/resources/js/pages/content/read.vue
Labels: frontend, backend

#79 Bump to 2.0.0-rc.5
  composer.json
Labels: dependencies

#80 Add fetch api
  src/resources/js/api/modules/badaso-content.js
Labels: frontend, feature

#81 Add fetch api
  src/resources/js/api/modules/badaso-content.js
Labels: frontend, feature

#82 Prepare next release
  src/resources/js/api/modules/badaso-content.js
Labels: frontend

#83 Bump version 2.0.0-rc.6
  composer.json
Labels: dependencies
