Repository uasoft-indonesia/badaso-content-module, pull requests merged in 2021-07, with the labels that each got.

#64 Update remade & composer
  README.md
  composer.json
Labels: dependencies

#67 Apply fixes from StyleCI
  src/Seeder/BadasoContentRolePermissionsSeeder.php
Labels: backend

#66 [Badaso v1] Bugfix/v1/update name
  CONTRIBUTING.md
  src/Seeder/BadasoContentFixedMenuItemSeeder.php
  src/Seeder/BadasoContentMenusSeeder.php
  src/Seeder/BadasoContentModuleSeeder.php
  src/Seeder/BadasoContentPermissionsSeeder.php
  src/Seeder/BadasoContentRolePermissionsSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/resources/js/api/modules/badaso-content.js
  src/resources/js/pages/content/add.vue
Labels: backend, bugfix, frontend

#68 [ Badaso v2 ] Bugfix/v2/update name
  CONTRIBUTING.md
  src/.DS_Store
  src/Commands/BadasoContentSetup.php
  src/Routes/api.php
  src/Seeder/BadasoContentFixedMenuItemSeeder.php
  src/Seeder/BadasoContentMenusSeeder.php
  src/Seeder/BadasoContentModuleSeeder.php
  src/Seeder/BadasoContentPermissionsSeeder.php
  src/Seeder/BadasoContentRolePermissionsSeeder.php
  src/resources/js/api/modules/badaso-content.js
  src/resources/js/components/BadasoContent.vue
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/components/index.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/index.vue
Labels: backend, bugfix, frontend

#69 Prepare for release 2.0.0-rc.3
  CONTRIBUTING.md
  composer.json
  src/.DS_Store
  src/Commands/BadasoContentSetup.php
  src/Routes/api.php
  src/Seeder/BadasoContentFixedMenuItemSeeder.php
  src/Seeder/BadasoContentMenusSeeder.php
  src/Seeder/BadasoContentModuleSeeder.php
  src/Seeder/BadasoContentPermissionsSeeder.php
  src/Seeder/BadasoContentRolePermissionsSeeder.php
  src/resources/js/api/modules/badaso-content.js
  src/resources/js/components/BadasoContent.vue
  src/resources/js/components/BadasoContentAddField.vue
  src/resources/js/components/index.js
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/index.vue
Labels: backend, dependencies, frontend

#71 Update content module for 1.x
  src/Controllers/ContentController.php
  src/Migrations/2021_04_01_090258_create_content_table.php
  src/Models/Content.php
  src/Seeder/BadasoContentFixedMenuItemSeeder.php
  src/Seeder/BadasoContentMenusSeeder.php
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/read.vue
Labels: backend, enhancement, frontend

#70 Update content module
  composer.json
  src/Controllers/ContentController.php
  src/Migrations/2021_04_01_090258_create_content_table.php
  src/Models/Content.php
  src/Seeder/BadasoContentFixedMenuItemSeeder.php
  src/Seeder/BadasoContentMenusSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/read.vue
Labels: backend, dependencies, enhancement, frontend

#72 Prepare 2.0.0-rc.4
  composer.json
  src/Controllers/ContentController.php
  src/Migrations/2021_04_01_090258_create_content_table.php
  src/Models/Content.php
  src/Seeder/BadasoContentFixedMenuItemSeeder.php
  src/Seeder/BadasoContentMenusSeeder.php
  src/Seeder/ContentModuleSeeder.php
  src/resources/js/pages/content/add.vue
  src/resources/js/pages/content/edit.vue
  src/resources/js/pages/content/read.vue
Labels: backend, dependencies, frontend
